### ISSUE TITLE
file upload blocking: doesn't unblock on failure

### ISSUE THREAD

**Issue by y-ack** [12Me21/sbs2#9]
it seems there are cases where file uploads will never return
attempting to upload a webm, for one
in these cases the 'upload file' will never be enabled again

expected behavior: even if the failure is unknown, 'cancel' button should force-enable the button again, since the point is to block unintentional double clicking more than anything.

**Comment by 12Me21** [comment]
oh...
trying to upload invalid images gives a 500 error so it keeps trying the request over and over..
I just disabled the automatic retry for 500 errors because I don't think that's useful anymore

probably would be better if I disabled retry completely except for certain types of requests (like, long poll requests to prevent that from failing) but oh well...
fixed by d2e97

**Comment by y-ack** [comment]
fixed by d2e97d2

**Comment by y-ack** [comment]
fixed by d2e97d2
